### ISSUE TITLE
Tags on GitHub?

### ISSUE THREAD

**Issue by vutran** [AlmeroSteyn/react-aria-live#9]
Hi,

I'm wondering if there is a reason why releases/tags are not available on this GitHub repo? I see the `CHANGELOG.md` file which is really helpful, but without a version commit, it's not easy to go through the commit history and see where each version changes.

**Comment by AlmeroSteyn** [comment]
Honestly, just did not get to it. The repo needs some love in other areas too but at this stage finding it hard to get the time to do that.

**Comment by vutran** [comment]
> Honestly, just did not get to it. The repo needs some love in other areas too but at this stage finding it hard to get the time to do that.

I see. Feel free to create what you want to get done in separate issues. I'm sure there's plenty of users that may find some time to help out. I may grab some as well but not sure what type of additions/changes you have in mind and it may solve some of my own issues as well.

:)

**Comment by AlmeroSteyn** [comment]
@vutran Sorry for taking so long to get back to this.

Just cut a release and will tag all releases from now on!

Main things I would like to do is to move the testing over to `react-testing-library` and also have a hooks alternative for the current render function.

I think it is a great idea to make issues of them. Please feel free to create feature requests as well if you find them while using this library.

**Comment by vutran** [comment]
Cool. Closing this since releases/tags are now available.
